//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilterAndSort {
	using System;
	using System.Collections.Generic;
	using System.IO;
	using System.Text;
	

	public partial class Employee {
		private byte[] photo;

		public int ID { get; set; }
		public string Email { get; set; }
		public string Password { get; set; }
		public string FirstName { get; set; }
		public string LastName { get; set; }
		public string Patronymic { get; set; }
		public byte[] Photo {
			get {
				if (photo == null) {
					FileStream fileStream = new FileStream("./no-photo.png", FileMode.Open, FileAccess.Read);
					photo = new byte[fileStream.Length];
					fileStream.Read(photo, 0, photo.Length);
				}
				return photo;
			}
			set {
				photo = value;
			}
		}
		public string Department { get; set; }
		public string Position { get; set; }

		// custom property for sorting
		public string FullName { get { return LastName + " " + FirstName + " " + Patronymic; } }

		public virtual Department Department1 { get; set; }
		public virtual Position Position1 { get; set; }
	}
}
